global using Ordering.Infrastructure.Data;
global using Ordering.API;
global using Ordering.Application;
global using Ordering.Infrastructure;
global using Ordering.Infrastructure.Extensions;
global using Carter;
global using Mapster;
global using MediatR;
global using Ordering.Application.Dtos;
