version: '3.4'

services:
   catalogdb:
      image: postgres
      networks:
        - mynetworks

   basketdb:
      image: postgres
      networks:
        - mynetworks

   distributedcache:
      image: redis

   catalog.api:
      image: ${DOCKER_REGISTRY-}catalogapi
      build:
        context: .
        dockerfile: Services/Catalog/Catalog.API/Dockerfile
      networks:
        - mynetworks



   basket.api:
      image: ${DOCKER_REGISTRY-}basketapi
      build:
          context: .
          dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
networks:
  mynetworks:
    driver: bridge

